x=int(input("Enter First Number"))
y=int(input("Enter Second Number"))
addition=(x+y)
subtraction=(x-y)
multiplication=(x*y)
division=(x/y)
average=((x+y)/2)
remainder=(x%y)
print(addition,subtraction,multiplication,division,average,remainder)
