import turtle
wn=turtle.Screen()
l= turtle.Turtle()
l.forward(100)
l.right(50)
l.forward(90)
l.right(40)
l.forward(90)
l.right(40)
l.forward(90)
l.right(50)
l.forward(100)
l.right(50)
l.forward(90)
l.right(40)
l.forward(90)
l.right(40)
l.forward(90)
wn.exitonclick()#finish the program by clicking on the graphics screen
